RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/Resource_Optimizer_Config__mdt.object-meta.xml
<CustomObject>
    <label>Resource Optimizer Config</label>
    <pluralLabel>Resource Optimizer Config</pluralLabel>
</CustomObject>

RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/fields/Are_your_Users_are_Resources__c.field-meta.xml
<CustomField>
    <fullName>Are_your_Users_are_Resources__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Are your Users are Resources?</label>
    <type>Checkbox</type>
</CustomField>

RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/fields/Do_you_allow_Overlay__c.field-meta.xml
<CustomField>
    <fullName>Do_you_allow_Overlay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do you allow Overlay?</label>
    <type>Checkbox</type>
</CustomField>

RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/fields/Do_you_allow_skill_based__c.field-meta.xml
<CustomField>
    <fullName>Do_you_allow_skill_based__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do you allow skill based assignment?</label>
    <type>Checkbox</type>
</CustomField>

RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/fields/Do_you_need_Resource_Grouping__c.field-meta.xml
<CustomField>
    <fullName>Do_you_need_Resource_Grouping__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do you need Resource Grouping?</label>
    <type>Checkbox</type>
</CustomField>

RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/fields/Organisation_business_hours_end_time__c.field-meta.xml
<CustomField>
    <fullName>Organisation_business_hours_end_time__c</fullName>
    <label>Organisation business hours end time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/fields/Organisation_business_hours_start_time__c.field-meta.xml
<CustomField>
    <fullName>Organisation_business_hours_start_time__c</fullName>
    <label>Organisation business hours start time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

RSOP/force-app/main/default/objects/Resource_Optimizer_Config__mdt/fields/Select_Profiles_to_create_Resources__c.field-meta.xml
<CustomField>
    <fullName>Select_Profiles_to_create_Resources__c</fullName>
    <label>Select Profiles to create Resources</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

RSOP/force-app/main/default/classes/roConfigSetupController.cls
public class roConfigSetupController {

    @AuraEnabled
    public static Resource_Optimizer_Config__mdt getMetadataRecord(){
        List<Resource_Optimizer_Config__mdt> configMetadata = [SELECT Id, MasterLabel, DeveloperName, 
            Are_your_Users_are_Resources__c, Do_you_allow_Overlay__c, Do_you_allow_skill_based__c, 
            Do_you_need_Resource_Grouping__c, Organisation_business_hours_end_time__c, 
            Organisation_business_hours_start_time__c, Select_Profiles_to_create_Resources__c 
            FROM Resource_Optimizer_Config__mdt WHERE DeveloperName = 'Resource_Optimizer_Config' LIMIT 1];
        
        if(configMetadata != null && configMetadata.size() > 0){
            return configMetadata[0];
        }
        else{
            return new Resource_Optimizer_Config__mdt();
        }
        
    }
}